project_id = "ulnsvkrrdcmfiguibkpx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.generate-weekly-workouts]
verify_jwt = false

[functions.generate-workout-monologue]
verify_jwt = false

[functions.workout-modifier]
verify_jwt = false

[functions.get-weather]
verify_jwt = false

[functions.process-pdf]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.generate-tiptap-document]
verify_jwt = false