name: mobile_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  audioplayers: ^5.2.1
  camera: ^0.10.5
  cloud_firestore: ^5.0.0
  dio: ^5.4.3
  firebase_auth: ^5.0.0
  firebase_core: ^3.15.2
  firebase_storage: ^12.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_isolate: ^2.0.4
  flutter_webrtc: ^0.9.47
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.5.1
  permission_handler: ^11.3.1
  tflite_flutter: ^0.12.1
  web_socket_channel: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/models/
    - .env
