name: strength_design
description: A new Flutter project for Strength Design.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  firebase_ui_auth: ^3.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.1
  go_router: ^16.2.4
  google_generative_ai: ^0.4.7
  health: ^13.2.0
  openfoodfacts: ^3.25.1
  path: ^1.9.0
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
