name: strength_design
description: A new Flutter project for Strength Design.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  firebase_core: ^4.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.1
  go_router: ^16.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
